/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as VerhalenRouteImport } from './routes/verhalen'
import { Route as TrajectRouteImport } from './routes/traject'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OverMijRouteImport } from './routes/over-mij'
import { Route as MaskingCheckRouteImport } from './routes/masking-check'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnergiescanRouteImport } from './routes/energiescan'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InformatieIndexRouteImport } from './routes/informatie/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as VoorWieLaatOntdektRouteImport } from './routes/voor-wie/laat-ontdekt'
import { Route as VoorWieAutistischeOndernemersRouteImport } from './routes/voor-wie/autistische-ondernemers'
import { Route as VoorWieAudhdOndernemersRouteImport } from './routes/voor-wie/audhd-ondernemers'
import { Route as VoorWieAdhdOndernemersRouteImport } from './routes/voor-wie/adhd-ondernemers'
import { Route as ThemasZichtbaarheidNetwerkenRouteImport } from './routes/themas/zichtbaarheid-netwerken'
import { Route as ThemasPrijzenOnderhandelenRouteImport } from './routes/themas/prijzen-onderhandelen'
import { Route as ThemasOverprikkelingRouteImport } from './routes/themas/overprikkeling'
import { Route as ThemasMaskingRouteImport } from './routes/themas/masking'
import { Route as ThemasExecutiveFunctiesRouteImport } from './routes/themas/executive-functies'
import { Route as ThemasEnergieBurnoutRouteImport } from './routes/themas/energie-burnout'
import { Route as ThemasDemandAvoidanceRouteImport } from './routes/themas/demand-avoidance'
import { Route as InformatieSlugRouteImport } from './routes/informatie/$slug'
import { Route as DownloadsSlugRouteImport } from './routes/downloads/$slug'

const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const VerhalenRoute = VerhalenRouteImport.update({
  id: '/verhalen',
  path: '/verhalen',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajectRoute = TrajectRouteImport.update({
  id: '/traject',
  path: '/traject',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OverMijRoute = OverMijRouteImport.update({
  id: '/over-mij',
  path: '/over-mij',
  getParentRoute: () => rootRouteImport,
} as any)
const MaskingCheckRoute = MaskingCheckRouteImport.update({
  id: '/masking-check',
  path: '/masking-check',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiescanRoute = EnergiescanRouteImport.update({
  id: '/energiescan',
  path: '/energiescan',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformatieIndexRoute = InformatieIndexRouteImport.update({
  id: '/informatie/',
  path: '/informatie/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DownloadsRoute,
} as any)
const VoorWieLaatOntdektRoute = VoorWieLaatOntdektRouteImport.update({
  id: '/voor-wie/laat-ontdekt',
  path: '/voor-wie/laat-ontdekt',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorWieAutistischeOndernemersRoute =
  VoorWieAutistischeOndernemersRouteImport.update({
    id: '/voor-wie/autistische-ondernemers',
    path: '/voor-wie/autistische-ondernemers',
    getParentRoute: () => rootRouteImport,
  } as any)
const VoorWieAudhdOndernemersRoute = VoorWieAudhdOndernemersRouteImport.update({
  id: '/voor-wie/audhd-ondernemers',
  path: '/voor-wie/audhd-ondernemers',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorWieAdhdOndernemersRoute = VoorWieAdhdOndernemersRouteImport.update({
  id: '/voor-wie/adhd-ondernemers',
  path: '/voor-wie/adhd-ondernemers',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemasZichtbaarheidNetwerkenRoute =
  ThemasZichtbaarheidNetwerkenRouteImport.update({
    id: '/themas/zichtbaarheid-netwerken',
    path: '/themas/zichtbaarheid-netwerken',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThemasPrijzenOnderhandelenRoute =
  ThemasPrijzenOnderhandelenRouteImport.update({
    id: '/themas/prijzen-onderhandelen',
    path: '/themas/prijzen-onderhandelen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThemasOverprikkelingRoute = ThemasOverprikkelingRouteImport.update({
  id: '/themas/overprikkeling',
  path: '/themas/overprikkeling',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemasMaskingRoute = ThemasMaskingRouteImport.update({
  id: '/themas/masking',
  path: '/themas/masking',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemasExecutiveFunctiesRoute = ThemasExecutiveFunctiesRouteImport.update({
  id: '/themas/executive-functies',
  path: '/themas/executive-functies',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemasEnergieBurnoutRoute = ThemasEnergieBurnoutRouteImport.update({
  id: '/themas/energie-burnout',
  path: '/themas/energie-burnout',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemasDemandAvoidanceRoute = ThemasDemandAvoidanceRouteImport.update({
  id: '/themas/demand-avoidance',
  path: '/themas/demand-avoidance',
  getParentRoute: () => rootRouteImport,
} as any)
const InformatieSlugRoute = InformatieSlugRouteImport.update({
  id: '/informatie/$slug',
  path: '/informatie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsSlugRoute = DownloadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DownloadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/energiescan': typeof EnergiescanRoute
  '/faq': typeof FaqRoute
  '/masking-check': typeof MaskingCheckRoute
  '/over-mij': typeof OverMijRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traject': typeof TrajectRoute
  '/verhalen': typeof VerhalenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/downloads/$slug': typeof DownloadsSlugRoute
  '/informatie/$slug': typeof InformatieSlugRoute
  '/themas/demand-avoidance': typeof ThemasDemandAvoidanceRoute
  '/themas/energie-burnout': typeof ThemasEnergieBurnoutRoute
  '/themas/executive-functies': typeof ThemasExecutiveFunctiesRoute
  '/themas/masking': typeof ThemasMaskingRoute
  '/themas/overprikkeling': typeof ThemasOverprikkelingRoute
  '/themas/prijzen-onderhandelen': typeof ThemasPrijzenOnderhandelenRoute
  '/themas/zichtbaarheid-netwerken': typeof ThemasZichtbaarheidNetwerkenRoute
  '/voor-wie/adhd-ondernemers': typeof VoorWieAdhdOndernemersRoute
  '/voor-wie/audhd-ondernemers': typeof VoorWieAudhdOndernemersRoute
  '/voor-wie/autistische-ondernemers': typeof VoorWieAutistischeOndernemersRoute
  '/voor-wie/laat-ontdekt': typeof VoorWieLaatOntdektRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/informatie/': typeof InformatieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/energiescan': typeof EnergiescanRoute
  '/faq': typeof FaqRoute
  '/masking-check': typeof MaskingCheckRoute
  '/over-mij': typeof OverMijRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traject': typeof TrajectRoute
  '/verhalen': typeof VerhalenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/downloads/$slug': typeof DownloadsSlugRoute
  '/informatie/$slug': typeof InformatieSlugRoute
  '/themas/demand-avoidance': typeof ThemasDemandAvoidanceRoute
  '/themas/energie-burnout': typeof ThemasEnergieBurnoutRoute
  '/themas/executive-functies': typeof ThemasExecutiveFunctiesRoute
  '/themas/masking': typeof ThemasMaskingRoute
  '/themas/overprikkeling': typeof ThemasOverprikkelingRoute
  '/themas/prijzen-onderhandelen': typeof ThemasPrijzenOnderhandelenRoute
  '/themas/zichtbaarheid-netwerken': typeof ThemasZichtbaarheidNetwerkenRoute
  '/voor-wie/adhd-ondernemers': typeof VoorWieAdhdOndernemersRoute
  '/voor-wie/audhd-ondernemers': typeof VoorWieAudhdOndernemersRoute
  '/voor-wie/autistische-ondernemers': typeof VoorWieAutistischeOndernemersRoute
  '/voor-wie/laat-ontdekt': typeof VoorWieLaatOntdektRoute
  '/downloads': typeof DownloadsIndexRoute
  '/informatie': typeof InformatieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRouteWithChildren
  '/energiescan': typeof EnergiescanRoute
  '/faq': typeof FaqRoute
  '/masking-check': typeof MaskingCheckRoute
  '/over-mij': typeof OverMijRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traject': typeof TrajectRoute
  '/verhalen': typeof VerhalenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/downloads/$slug': typeof DownloadsSlugRoute
  '/informatie/$slug': typeof InformatieSlugRoute
  '/themas/demand-avoidance': typeof ThemasDemandAvoidanceRoute
  '/themas/energie-burnout': typeof ThemasEnergieBurnoutRoute
  '/themas/executive-functies': typeof ThemasExecutiveFunctiesRoute
  '/themas/masking': typeof ThemasMaskingRoute
  '/themas/overprikkeling': typeof ThemasOverprikkelingRoute
  '/themas/prijzen-onderhandelen': typeof ThemasPrijzenOnderhandelenRoute
  '/themas/zichtbaarheid-netwerken': typeof ThemasZichtbaarheidNetwerkenRoute
  '/voor-wie/adhd-ondernemers': typeof VoorWieAdhdOndernemersRoute
  '/voor-wie/audhd-ondernemers': typeof VoorWieAudhdOndernemersRoute
  '/voor-wie/autistische-ondernemers': typeof VoorWieAutistischeOndernemersRoute
  '/voor-wie/laat-ontdekt': typeof VoorWieLaatOntdektRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/informatie/': typeof InformatieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/downloads'
    | '/energiescan'
    | '/faq'
    | '/masking-check'
    | '/over-mij'
    | '/privacy'
    | '/sitemap.xml'
    | '/traject'
    | '/verhalen'
    | '/voorwaarden'
    | '/werkwijze'
    | '/downloads/$slug'
    | '/informatie/$slug'
    | '/themas/demand-avoidance'
    | '/themas/energie-burnout'
    | '/themas/executive-functies'
    | '/themas/masking'
    | '/themas/overprikkeling'
    | '/themas/prijzen-onderhandelen'
    | '/themas/zichtbaarheid-netwerken'
    | '/voor-wie/adhd-ondernemers'
    | '/voor-wie/audhd-ondernemers'
    | '/voor-wie/autistische-ondernemers'
    | '/voor-wie/laat-ontdekt'
    | '/downloads/'
    | '/informatie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/energiescan'
    | '/faq'
    | '/masking-check'
    | '/over-mij'
    | '/privacy'
    | '/sitemap.xml'
    | '/traject'
    | '/verhalen'
    | '/voorwaarden'
    | '/werkwijze'
    | '/downloads/$slug'
    | '/informatie/$slug'
    | '/themas/demand-avoidance'
    | '/themas/energie-burnout'
    | '/themas/executive-functies'
    | '/themas/masking'
    | '/themas/overprikkeling'
    | '/themas/prijzen-onderhandelen'
    | '/themas/zichtbaarheid-netwerken'
    | '/voor-wie/adhd-ondernemers'
    | '/voor-wie/audhd-ondernemers'
    | '/voor-wie/autistische-ondernemers'
    | '/voor-wie/laat-ontdekt'
    | '/downloads'
    | '/informatie'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/downloads'
    | '/energiescan'
    | '/faq'
    | '/masking-check'
    | '/over-mij'
    | '/privacy'
    | '/sitemap.xml'
    | '/traject'
    | '/verhalen'
    | '/voorwaarden'
    | '/werkwijze'
    | '/downloads/$slug'
    | '/informatie/$slug'
    | '/themas/demand-avoidance'
    | '/themas/energie-burnout'
    | '/themas/executive-functies'
    | '/themas/masking'
    | '/themas/overprikkeling'
    | '/themas/prijzen-onderhandelen'
    | '/themas/zichtbaarheid-netwerken'
    | '/voor-wie/adhd-ondernemers'
    | '/voor-wie/audhd-ondernemers'
    | '/voor-wie/autistische-ondernemers'
    | '/voor-wie/laat-ontdekt'
    | '/downloads/'
    | '/informatie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRouteWithChildren
  EnergiescanRoute: typeof EnergiescanRoute
  FaqRoute: typeof FaqRoute
  MaskingCheckRoute: typeof MaskingCheckRoute
  OverMijRoute: typeof OverMijRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrajectRoute: typeof TrajectRoute
  VerhalenRoute: typeof VerhalenRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
  InformatieSlugRoute: typeof InformatieSlugRoute
  ThemasDemandAvoidanceRoute: typeof ThemasDemandAvoidanceRoute
  ThemasEnergieBurnoutRoute: typeof ThemasEnergieBurnoutRoute
  ThemasExecutiveFunctiesRoute: typeof ThemasExecutiveFunctiesRoute
  ThemasMaskingRoute: typeof ThemasMaskingRoute
  ThemasOverprikkelingRoute: typeof ThemasOverprikkelingRoute
  ThemasPrijzenOnderhandelenRoute: typeof ThemasPrijzenOnderhandelenRoute
  ThemasZichtbaarheidNetwerkenRoute: typeof ThemasZichtbaarheidNetwerkenRoute
  VoorWieAdhdOndernemersRoute: typeof VoorWieAdhdOndernemersRoute
  VoorWieAudhdOndernemersRoute: typeof VoorWieAudhdOndernemersRoute
  VoorWieAutistischeOndernemersRoute: typeof VoorWieAutistischeOndernemersRoute
  VoorWieLaatOntdektRoute: typeof VoorWieLaatOntdektRoute
  InformatieIndexRoute: typeof InformatieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verhalen': {
      id: '/verhalen'
      path: '/verhalen'
      fullPath: '/verhalen'
      preLoaderRoute: typeof VerhalenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traject': {
      id: '/traject'
      path: '/traject'
      fullPath: '/traject'
      preLoaderRoute: typeof TrajectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-mij': {
      id: '/over-mij'
      path: '/over-mij'
      fullPath: '/over-mij'
      preLoaderRoute: typeof OverMijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masking-check': {
      id: '/masking-check'
      path: '/masking-check'
      fullPath: '/masking-check'
      preLoaderRoute: typeof MaskingCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energiescan': {
      id: '/energiescan'
      path: '/energiescan'
      fullPath: '/energiescan'
      preLoaderRoute: typeof EnergiescanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informatie/': {
      id: '/informatie/'
      path: '/informatie'
      fullPath: '/informatie/'
      preLoaderRoute: typeof InformatieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof DownloadsRoute
    }
    '/voor-wie/laat-ontdekt': {
      id: '/voor-wie/laat-ontdekt'
      path: '/voor-wie/laat-ontdekt'
      fullPath: '/voor-wie/laat-ontdekt'
      preLoaderRoute: typeof VoorWieLaatOntdektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie/autistische-ondernemers': {
      id: '/voor-wie/autistische-ondernemers'
      path: '/voor-wie/autistische-ondernemers'
      fullPath: '/voor-wie/autistische-ondernemers'
      preLoaderRoute: typeof VoorWieAutistischeOndernemersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie/audhd-ondernemers': {
      id: '/voor-wie/audhd-ondernemers'
      path: '/voor-wie/audhd-ondernemers'
      fullPath: '/voor-wie/audhd-ondernemers'
      preLoaderRoute: typeof VoorWieAudhdOndernemersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie/adhd-ondernemers': {
      id: '/voor-wie/adhd-ondernemers'
      path: '/voor-wie/adhd-ondernemers'
      fullPath: '/voor-wie/adhd-ondernemers'
      preLoaderRoute: typeof VoorWieAdhdOndernemersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/zichtbaarheid-netwerken': {
      id: '/themas/zichtbaarheid-netwerken'
      path: '/themas/zichtbaarheid-netwerken'
      fullPath: '/themas/zichtbaarheid-netwerken'
      preLoaderRoute: typeof ThemasZichtbaarheidNetwerkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/prijzen-onderhandelen': {
      id: '/themas/prijzen-onderhandelen'
      path: '/themas/prijzen-onderhandelen'
      fullPath: '/themas/prijzen-onderhandelen'
      preLoaderRoute: typeof ThemasPrijzenOnderhandelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/overprikkeling': {
      id: '/themas/overprikkeling'
      path: '/themas/overprikkeling'
      fullPath: '/themas/overprikkeling'
      preLoaderRoute: typeof ThemasOverprikkelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/masking': {
      id: '/themas/masking'
      path: '/themas/masking'
      fullPath: '/themas/masking'
      preLoaderRoute: typeof ThemasMaskingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/executive-functies': {
      id: '/themas/executive-functies'
      path: '/themas/executive-functies'
      fullPath: '/themas/executive-functies'
      preLoaderRoute: typeof ThemasExecutiveFunctiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/energie-burnout': {
      id: '/themas/energie-burnout'
      path: '/themas/energie-burnout'
      fullPath: '/themas/energie-burnout'
      preLoaderRoute: typeof ThemasEnergieBurnoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themas/demand-avoidance': {
      id: '/themas/demand-avoidance'
      path: '/themas/demand-avoidance'
      fullPath: '/themas/demand-avoidance'
      preLoaderRoute: typeof ThemasDemandAvoidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informatie/$slug': {
      id: '/informatie/$slug'
      path: '/informatie/$slug'
      fullPath: '/informatie/$slug'
      preLoaderRoute: typeof InformatieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/$slug': {
      id: '/downloads/$slug'
      path: '/$slug'
      fullPath: '/downloads/$slug'
      preLoaderRoute: typeof DownloadsSlugRouteImport
      parentRoute: typeof DownloadsRoute
    }
  }
}

interface DownloadsRouteChildren {
  DownloadsSlugRoute: typeof DownloadsSlugRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
}

const DownloadsRouteChildren: DownloadsRouteChildren = {
  DownloadsSlugRoute: DownloadsSlugRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
}

const DownloadsRouteWithChildren = DownloadsRoute._addFileChildren(
  DownloadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRouteWithChildren,
  EnergiescanRoute: EnergiescanRoute,
  FaqRoute: FaqRoute,
  MaskingCheckRoute: MaskingCheckRoute,
  OverMijRoute: OverMijRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrajectRoute: TrajectRoute,
  VerhalenRoute: VerhalenRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  WerkwijzeRoute: WerkwijzeRoute,
  InformatieSlugRoute: InformatieSlugRoute,
  ThemasDemandAvoidanceRoute: ThemasDemandAvoidanceRoute,
  ThemasEnergieBurnoutRoute: ThemasEnergieBurnoutRoute,
  ThemasExecutiveFunctiesRoute: ThemasExecutiveFunctiesRoute,
  ThemasMaskingRoute: ThemasMaskingRoute,
  ThemasOverprikkelingRoute: ThemasOverprikkelingRoute,
  ThemasPrijzenOnderhandelenRoute: ThemasPrijzenOnderhandelenRoute,
  ThemasZichtbaarheidNetwerkenRoute: ThemasZichtbaarheidNetwerkenRoute,
  VoorWieAdhdOndernemersRoute: VoorWieAdhdOndernemersRoute,
  VoorWieAudhdOndernemersRoute: VoorWieAudhdOndernemersRoute,
  VoorWieAutistischeOndernemersRoute: VoorWieAutistischeOndernemersRoute,
  VoorWieLaatOntdektRoute: VoorWieLaatOntdektRoute,
  InformatieIndexRoute: InformatieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
