/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as TrajectRouteImport } from './routes/traject'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OverMijRouteImport } from './routes/over-mij'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajectRoute = TrajectRouteImport.update({
  id: '/traject',
  path: '/traject',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OverMijRoute = OverMijRouteImport.update({
  id: '/over-mij',
  path: '/over-mij',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/over-mij': typeof OverMijRoute
  '/privacy': typeof PrivacyRoute
  '/traject': typeof TrajectRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/werkwijze': typeof WerkwijzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/over-mij': typeof OverMijRoute
  '/privacy': typeof PrivacyRoute
  '/traject': typeof TrajectRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/werkwijze': typeof WerkwijzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/over-mij': typeof OverMijRoute
  '/privacy': typeof PrivacyRoute
  '/traject': typeof TrajectRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/werkwijze': typeof WerkwijzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/over-mij'
    | '/privacy'
    | '/traject'
    | '/voorwaarden'
    | '/werkwijze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/over-mij'
    | '/privacy'
    | '/traject'
    | '/voorwaarden'
    | '/werkwijze'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/over-mij'
    | '/privacy'
    | '/traject'
    | '/voorwaarden'
    | '/werkwijze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OverMijRoute: typeof OverMijRoute
  PrivacyRoute: typeof PrivacyRoute
  TrajectRoute: typeof TrajectRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traject': {
      id: '/traject'
      path: '/traject'
      fullPath: '/traject'
      preLoaderRoute: typeof TrajectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-mij': {
      id: '/over-mij'
      path: '/over-mij'
      fullPath: '/over-mij'
      preLoaderRoute: typeof OverMijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OverMijRoute: OverMijRoute,
  PrivacyRoute: PrivacyRoute,
  TrajectRoute: TrajectRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  WerkwijzeRoute: WerkwijzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
